-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  participant_name text,
  participant_email text,
  product_name text,
  product_version text,
  start_date date,
  baseline_days integer,
  dose_notes text,
  default_dose integer,
  mode text,
  estimates jsonb,
  reminders jsonb
);

-- Create daily_logs table
create table public.daily_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  date date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  took_dose text,
  dose_amount numeric,
  sliders jsonb,
  wake_ups numeric,
  wearables jsonb,
  metrics jsonb,
  notes text,
  unique(user_id, date)
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.daily_logs enable row level security;

create policy "Users can view own profile" on public.profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "Users can insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can view own logs" on public.daily_logs
  for select using (auth.uid() = user_id);

create policy "Users can insert own logs" on public.daily_logs
  for insert with check (auth.uid() = user_id);

create policy "Users can update own logs" on public.daily_logs
  for update using (auth.uid() = user_id);
